#include "errors.h"


// Error messages
char* errors[ERRORS_NUMBER] = {	
	":= symbol was expected",
	"ASSIGNEMENT OR PROCEDURE was expected",
	"BEGIN symbol was expected",
	"A character was expected",
	") symbol was expected",
	"error on CONDITION ",
	"DECLARATIVE PART ERROR",
	": symbol was expected ",
	": symboll was expected ",
	"DPUN_ERROR",
	"END symbol was expected",
	"EXPRESSION error",
	"FACTOR ERROR",
	"error sequence of statements handled",
	"identifier was expected",
	"IS symbol was expected",
	"; symbol was expected",
	"symbol not found error",
	"IF symbol was expected",
	"Mode error",
	"parameter profile errror",
	"parameter specification error",
	") symbol was expected",
	"( symbol was expected",
	"procedure was expected",
	"RELATION EXPECTED ERROR",
	"SEQUENCE STATEMENT ERROR",
	"SIMPLE EXPRESSION ERROR",
	" ' symbol was expected",
	"Type error",
	"TERM ERROR",
	"THEN symbol was expected",
	"Unrecognized character",
	": symbol was expected",
	"; symbol was expected",
	"symbol exist error",
	"LOOP symbol was expected"




	
};


/*
 * Function called to raise an errors generated by
 * the compiler
 */
void raise_error(error_code ec) { 
		WritePseudoCodeFile = true;
		printf("Error number %i: %s on line %i \n", ec, errors[ec], current_line);
}

