#include "errors.h"


// Error messages
char* errors[ERRORS_NUMBER] = {
	"Unrecognized character",
	"A single quote was expected",
	"A character was expected",
};


/*
 * Function called to raise an errors generated by
 * the compiler
 */
void raise_error(error_code ec) {
	if (ec >= ERRORS_NUMBER)
		printf("Error number %i: error without a message yet on line %i \n", ec, current_line);
	else 
		printf("Error number %i: %s on line %i \n", ec, errors[ec], current_line);
}