#include "global.h"

#define ERRORS_NUMBER	3


typedef enum _error_codes {
	UNRECOGNIZED_CHARACTER_ERROR,
	SINGLE_QUOTE_EXPECTED_ERROR,
	CHARACTER_EXPECTED_ERROR,
	IDENTIFIER_EXPECTED_ERROR,
	AFFECTATION_SYMBOL_EXPECTED_ERROR,
	SEMICOLON_EXPECTED_ERROR,
<<<<<<< HEAD
	SYMBOL_NOT_FOUND_ERROR,
=======
	IF_EXPECTED_ERROR,
	THEN_EXPECTED_ERROR,
	BEGIN_EXPECTED_ERROR,
	END_EXPECTED_ERROR,
	IS_EXPECTED_ERROR,
	PROCEDURE_EXPECTED_ERROR,
	PO_EXPECTED_ERROR,
	PF_EXPECTED_ERROR,
	DEUXPOINT_EXPECTED_ERROR
>>>>>>> 632770b2e9e49d8c66e76d8bdf8b4af44fd2d4f2
} error_code;


void raise_error(error_code);
